server:
  port: 10000

#MyBatis
log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@//localhost:1521/XE
      username: hr
      password: hr

#이메일 변수
myapp:
  email: 17gallevent@gmail.com
  password: isxbkfyffkdwbsax

#파일 경로 설정
file:
  dir: D:/project/upload/
